### ISSUE TITLE
[Bug] Model Files Fail to Train

### ISSUE THREAD

**Issue by mr-segfault** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#204]
Using the current version (pulled moments before writing this), I try to 'one click train' and it performs the Process Data / Feature Extraction steps but then then crashes without training any models. This is in addition to another bug ([167](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/167)) that is unable to write the index file. 

**(truncated text)**
now-169,all-160,7_1.wav,(149, 256)
7_2.wav-contains nan
7_4.wav-contains nan
8_0.wav-contains nan
8_1.wav-contains nan
8_3.wav-contains nan
8_4.wav-contains nan
9_1.wav-contains nan
9_2.wav-contains nan
all-feature-done

Traceback (most recent call last):
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 7, in <module>
    hps = utils.get_hparams()
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/train/utils.py", line 363, in get_hparams
    config = json.loads(data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 47 column 1 (char 1047)
Traceback (most recent call last):
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/blocks.py", line 1039, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 894, in train1key
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by fumiama** [comment]
Your training dataset is too short.

**Comment by mr-segfault** [comment]
50 files ~ 6 minutes is too short?

**Comment by mr-segfault** [comment]
The error log is truncated here is the entire output start to finish:
(Retrieval-based-Voice-Conversion-WebUI) user@section9:~/Retrieval-based-Voice-Conversion-WebUI$ python infer-web.py 
Use Language: en_US
16系显卡强制单精度
Running on local URL:  http://0.0.0.0:7865
start preprocess
['trainset_preprocess_pipeline_print.py', '/home/user/Music/dataset_hj/40k/Minidata', '40000', '8', '/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test', 'False']
/home/user/Music/dataset_hj/40k/Minidata/04_fai_04_28_111.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/10_fai_10_28_106.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_004.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/24_fai_24_28_064.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_014.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_059.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/SUPER_BOWL_ZUCCHINI_Raw_Audio_131935027_000.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/04_fai_04_28_118.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/12_fai_12_28_013.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_027.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/24_fai_24_28_066.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_020.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_063.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/SUPER_BOWL_ZUCCHINI_Raw_Audio_131935027_004.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/09_fai_09_28_038.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/14_fai_14_28_247.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_028.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_043.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_021.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_066-2.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_000.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/15_fai_15_28_164.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_104.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_050.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_031.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_072.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_003.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/16_fai_16_28_241.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/23_fai_23_28_109.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_082.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_032-1.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_073.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_004.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/16_fai_16_28_245.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/23_fai_23_28_146.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_122.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_032-2.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_086.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_005.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/19_fai_19_28_050.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/23_fai_23_28_150.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_188.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_039.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_100.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/10_fai_10_28_002.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/21_fai_21_28_139.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/24_fai_24_28_040.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_000.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_041.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_103.wav->Suc.
end preprocess
start preprocess
['trainset_preprocess_pipeline_print.py', '/home/user/Music/dataset_hj/40k/Minidata', '40000', '8', '/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test', 'False']
/home/user/Music/dataset_hj/40k/Minidata/04_fai_04_28_111.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/10_fai_10_28_106.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_004.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/24_fai_24_28_064.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_014.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_059.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/SUPER_BOWL_ZUCCHINI_Raw_Audio_131935027_000.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/04_fai_04_28_118.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/12_fai_12_28_013.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_027.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/24_fai_24_28_066.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_020.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_063.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/SUPER_BOWL_ZUCCHINI_Raw_Audio_131935027_004.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/09_fai_09_28_038.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/14_fai_14_28_247.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_028.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_043.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_021.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_066-2.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_000.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/15_fai_15_28_164.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/22_fai_22_28_104.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_050.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_031.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_072.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_003.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/16_fai_16_28_241.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/23_fai_23_28_109.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_082.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_032-1.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_073.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_004.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/16_fai_16_28_245.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/23_fai_23_28_146.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_122.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_032-2.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_086.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/107badstuffvx_005.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/19_fai_19_28_050.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/23_fai_23_28_150.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/25_fai_25_28_188.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_039.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_100.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/10_fai_10_28_002.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/21_fai_21_28_139.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/24_fai_24_28_040.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_000.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_041.wav->Suc.
/home/user/Music/dataset_hj/40k/Minidata/BBS1E1_103.wav->Suc.
end preprocess

['extract_f0_print.py', '/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test', '8', 'harvest']
todo-f0-22
f0ing,now-0,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_0.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_1.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_2.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_4.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_5.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_0.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_1.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_2.wav
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:89: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  f0_coarse = np.rint(f0_mel).astype(np.int)
/home/user/Retrieval-based-Voice-Conversion-WebUI/extract_f0_print.py:38: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x, sr = librosa.load(path, self.fs)  # , res_type='soxr_vhq'
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_3.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_1.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/19_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/16_3.wav
f0ing,now-4,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/16_1.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/17_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/17_2.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_3.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/25_0.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_5.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/25_1.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_1.wav
f0ing,now-8,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/23_4.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_2.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_6.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_3.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/34_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/32_2.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/32_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/31_2.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_1.wav
f0ing,now-12,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/31_0.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_3.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_3.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_1.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_4.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_0.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_1.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_4.wav
f0ing,now-16,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/43_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_0.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/9_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_3.wav
f0ing,now-20,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_4.wav
['extract_f0_print.py', '/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test', '8', 'harvest']
todo-f0-22
f0ing,now-0,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_0.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_1.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_2.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_4.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_5.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_0.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_1.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_2.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_3.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_1.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/19_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/16_3.wav
f0ing,now-4,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/16_1.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/17_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/17_2.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_3.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/25_0.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_5.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/25_1.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_1.wav
f0ing,now-8,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/23_4.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_2.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_6.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_3.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/34_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/32_2.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/32_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/31_2.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_1.wav
f0ing,now-12,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/31_0.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_3.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_3.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_1.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_4.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_0.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_1.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_4.wav
f0ing,now-16,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/43_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_0.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/9_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_3.wav
f0ing,now-20,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_4.wav

['extract_feature_print.py', 'cuda:0', '1', '0', '0', '/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test']
/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test
load model(s) from hubert_base.pt
2023-04-28 21:17:53 | INFO | fairseq.tasks.hubert_pretraining | current directory is /home/user/Retrieval-based-Voice-Conversion-WebUI
2023-04-28 21:17:53 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-04-28 21:17:53 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
move model to cuda
all-feature-169
0_0.wav-contains nan
now-169,all-0,0_0.wav,(149, 256)
0_1.wav-contains nan
0_2.wav-contains nan
0_4.wav-contains nan
0_5.wav-contains nan
10_0.wav-contains nan
10_1.wav-contains nan
10_2.wav-contains nan
10_4.wav-contains nan
10_5.wav-contains nan
11_0.wav-contains nan
11_1.wav-contains nan
11_2.wav-contains nan
11_4.wav-contains nan
11_5.wav-contains nan
12_0.wav-contains nan
12_2.wav-contains nan
now-169,all-16,12_2.wav,(149, 256)
12_4.wav-contains nan
12_5.wav-contains nan
13_0.wav-contains nan
13_1.wav-contains nan
13_3.wav-contains nan
13_4.wav-contains nan
14_0.wav-contains nan
14_1.wav-contains nan
14_2.wav-contains nan
14_4.wav-contains nan
15_0.wav-contains nan
15_1.wav-contains nan
15_2.wav-contains nan
15_4.wav-contains nan
15_5.wav-contains nan
16_1.wav-contains nan
now-169,all-32,16_1.wav,(149, 256)
16_3.wav-contains nan
17_0.wav-contains nan
17_2.wav-contains nan
18_0.wav-contains nan
18_1.wav-contains nan
18_3.wav-contains nan
19_0.wav-contains nan
19_1.wav-contains nan
19_2.wav-contains nan
19_4.wav-contains nan
19_5.wav-contains nan
1_0.wav-contains nan
1_1.wav-contains nan
1_2.wav-contains nan
1_4.wav-contains nan
20_0.wav-contains nan
now-169,all-48,20_0.wav,(149, 256)
20_1.wav-contains nan
20_2.wav-contains nan
20_4.wav-contains nan
21_0.wav-contains nan
21_1.wav-contains nan
21_2.wav-contains nan
21_4.wav-contains nan
21_5.wav-contains nan
22_0.wav-contains nan
22_2.wav-contains nan
22_4.wav-contains nan
22_5.wav-contains nan
23_0.wav-contains nan
23_1.wav-contains nan
23_2.wav-contains nan
23_4.wav-contains nan
now-169,all-64,23_4.wav,(115, 256)
24_1.wav-contains nan
24_2.wav-contains nan
24_3.wav-contains nan
24_5.wav-contains nan
24_6.wav-contains nan
25_0.wav-contains nan
25_1.wav-contains nan
25_2.wav-contains nan
25_4.wav-contains nan
25_5.wav-contains nan
26_0.wav-contains nan
26_2.wav-contains nan
27_0.wav-contains nan
27_1.wav-contains nan
27_3.wav-contains nan
28_0.wav-contains nan
now-169,all-80,28_0.wav,(149, 256)
28_1.wav-contains nan
28_2.wav-contains nan
28_4.wav-contains nan
28_5.wav-contains nan
29_0.wav-contains nan
29_2.wav-contains nan
29_3.wav-contains nan
2_0.wav-contains nan
2_1.wav-contains nan
2_2.wav-contains nan
2_4.wav-contains nan
30_0.wav-contains nan
30_1.wav-contains nan
30_3.wav-contains nan
30_4.wav-contains nan
31_0.wav-contains nan
now-169,all-96,31_0.wav,(149, 256)
31_2.wav-contains nan
32_0.wav-contains nan
32_2.wav-contains nan
33_0.wav-contains nan
33_1.wav-contains nan
33_3.wav-contains nan
34_0.wav-contains nan
34_1.wav-contains nan
34_3.wav-contains nan
35_0.wav-contains nan
35_2.wav-contains nan
36_0.wav-contains nan
36_2.wav-contains nan
37_0.wav-contains nan
37_1.wav-contains nan
37_3.wav-contains nan
now-169,all-112,37_3.wav,(84, 256)
38_0.wav-contains nan
38_2.wav-contains nan
39_0.wav-contains nan
39_1.wav-contains nan
39_3.wav-contains nan
3_0.wav-contains nan
3_2.wav-contains nan
40_0.wav-contains nan
40_2.wav-contains nan
41_0.wav-contains nan
41_2.wav-contains nan
42_0.wav-contains nan
42_1.wav-contains nan
42_3.wav-contains nan
43_0.wav-contains nan
43_2.wav-contains nan
now-169,all-128,43_2.wav,(117, 256)
44_0.wav-contains nan
44_1.wav-contains nan
44_3.wav-contains nan
45_1.wav-contains nan
45_2.wav-contains nan
45_3.wav-contains nan
45_4.wav-contains nan
45_5.wav-contains nan
45_6.wav-contains nan
46_0.wav-contains nan
46_2.wav-contains nan
47_0.wav-contains nan
47_2.wav-contains nan
48_0.wav-contains nan
48_2.wav-contains nan
48_3.wav-contains nan
now-169,all-144,48_3.wav,(42, 256)
49_0.wav-contains nan
49_2.wav-contains nan
49_4.wav-contains nan
4_0.wav-contains nan
4_1.wav-contains nan
4_3.wav-contains nan
5_0.wav-contains nan
5_1.wav-contains nan
5_3.wav-contains nan
6_0.wav-contains nan
6_1.wav-contains nan
6_2.wav-contains nan
6_3.wav-contains nan
6_5.wav-contains nan
7_0.wav-contains nan
7_1.wav-contains nan
now-169,all-160,7_1.wav,(149, 256)
7_2.wav-contains nan
7_4.wav-contains nan
8_0.wav-contains nan
8_1.wav-contains nan
8_3.wav-contains nan
8_4.wav-contains nan
9_1.wav-contains nan
9_2.wav-contains nan
all-feature-done
['extract_f0_print.py', '/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test', '8', 'harvest']
todo-f0-22
f0ing,now-0,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_0.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_1.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_2.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_4.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/0_5.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_0.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_1.wav
todo-f0-21
f0ing,now-0,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/10_2.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_3.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/18_1.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/19_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/16_3.wav
f0ing,now-4,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/16_1.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/17_0.wav
f0ing,now-4,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/17_2.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_3.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/25_0.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_5.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/25_1.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_1.wav
f0ing,now-8,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/23_4.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_2.wav
f0ing,now-8,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/24_6.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_3.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/34_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/32_2.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/32_0.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/31_2.wav
f0ing,now-12,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/33_1.wav
f0ing,now-12,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/31_0.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_3.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_3.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_1.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_4.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_0.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/44_1.wav
f0ing,now-16,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/45_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_4.wav
f0ing,now-16,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/43_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_0.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/9_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_2.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/8_3.wav
f0ing,now-20,all-22,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_1.wav
f0ing,now-20,all-21,-/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test/1_16k_wavs/7_4.wav
['extract_feature_print.py', 'cuda:0', '1', '0', '0', '/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test']
/home/user/Retrieval-based-Voice-Conversion-WebUI/logs/mi-test
load model(s) from hubert_base.pt
move model to cuda
all-feature-169
0_0.wav-contains nan
now-169,all-0,0_0.wav,(149, 256)
0_1.wav-contains nan
0_2.wav-contains nan
0_4.wav-contains nan
0_5.wav-contains nan
10_0.wav-contains nan
10_1.wav-contains nan
10_2.wav-contains nan
10_4.wav-contains nan
10_5.wav-contains nan
11_0.wav-contains nan
11_1.wav-contains nan
11_2.wav-contains nan
11_4.wav-contains nan
11_5.wav-contains nan
12_0.wav-contains nan
12_2.wav-contains nan
now-169,all-16,12_2.wav,(149, 256)
12_4.wav-contains nan
12_5.wav-contains nan
13_0.wav-contains nan
13_1.wav-contains nan
13_3.wav-contains nan
13_4.wav-contains nan
14_0.wav-contains nan
14_1.wav-contains nan
14_2.wav-contains nan
14_4.wav-contains nan
15_0.wav-contains nan
15_1.wav-contains nan
15_2.wav-contains nan
15_4.wav-contains nan
15_5.wav-contains nan
16_1.wav-contains nan
now-169,all-32,16_1.wav,(149, 256)
16_3.wav-contains nan
17_0.wav-contains nan
17_2.wav-contains nan
18_0.wav-contains nan
18_1.wav-contains nan
18_3.wav-contains nan
19_0.wav-contains nan
19_1.wav-contains nan
19_2.wav-contains nan
19_4.wav-contains nan
19_5.wav-contains nan
1_0.wav-contains nan
1_1.wav-contains nan
1_2.wav-contains nan
1_4.wav-contains nan
20_0.wav-contains nan
now-169,all-48,20_0.wav,(149, 256)
20_1.wav-contains nan
20_2.wav-contains nan
20_4.wav-contains nan
21_0.wav-contains nan
21_1.wav-contains nan
21_2.wav-contains nan
21_4.wav-contains nan
21_5.wav-contains nan
22_0.wav-contains nan
22_2.wav-contains nan
22_4.wav-contains nan
22_5.wav-contains nan
23_0.wav-contains nan
23_1.wav-contains nan
23_2.wav-contains nan
23_4.wav-contains nan
now-169,all-64,23_4.wav,(115, 256)
24_1.wav-contains nan
24_2.wav-contains nan
24_3.wav-contains nan
24_5.wav-contains nan
24_6.wav-contains nan
25_0.wav-contains nan
25_1.wav-contains nan
25_2.wav-contains nan
25_4.wav-contains nan
25_5.wav-contains nan
26_0.wav-contains nan
26_2.wav-contains nan
27_0.wav-contains nan
27_1.wav-contains nan
27_3.wav-contains nan
28_0.wav-contains nan
now-169,all-80,28_0.wav,(149, 256)
28_1.wav-contains nan
28_2.wav-contains nan
28_4.wav-contains nan
28_5.wav-contains nan
29_0.wav-contains nan
29_2.wav-contains nan
29_3.wav-contains nan
2_0.wav-contains nan
2_1.wav-contains nan
2_2.wav-contains nan
2_4.wav-contains nan
30_0.wav-contains nan
30_1.wav-contains nan
30_3.wav-contains nan
30_4.wav-contains nan
31_0.wav-contains nan
now-169,all-96,31_0.wav,(149, 256)
31_2.wav-contains nan
32_0.wav-contains nan
32_2.wav-contains nan
33_0.wav-contains nan
33_1.wav-contains nan
33_3.wav-contains nan
34_0.wav-contains nan
34_1.wav-contains nan
34_3.wav-contains nan
35_0.wav-contains nan
35_2.wav-contains nan
36_0.wav-contains nan
36_2.wav-contains nan
37_0.wav-contains nan
37_1.wav-contains nan
37_3.wav-contains nan
now-169,all-112,37_3.wav,(84, 256)
38_0.wav-contains nan
38_2.wav-contains nan
39_0.wav-contains nan
39_1.wav-contains nan
39_3.wav-contains nan
3_0.wav-contains nan
3_2.wav-contains nan
40_0.wav-contains nan
40_2.wav-contains nan
41_0.wav-contains nan
41_2.wav-contains nan
42_0.wav-contains nan
42_1.wav-contains nan
42_3.wav-contains nan
43_0.wav-contains nan
43_2.wav-contains nan
now-169,all-128,43_2.wav,(117, 256)
44_0.wav-contains nan
44_1.wav-contains nan
44_3.wav-contains nan
45_1.wav-contains nan
45_2.wav-contains nan
45_3.wav-contains nan
45_4.wav-contains nan
45_5.wav-contains nan
45_6.wav-contains nan
46_0.wav-contains nan
46_2.wav-contains nan
47_0.wav-contains nan
47_2.wav-contains nan
48_0.wav-contains nan
48_2.wav-contains nan
48_3.wav-contains nan
now-169,all-144,48_3.wav,(42, 256)
49_0.wav-contains nan
49_2.wav-contains nan
49_4.wav-contains nan
4_0.wav-contains nan
4_1.wav-contains nan
4_3.wav-contains nan
5_0.wav-contains nan
5_1.wav-contains nan
5_3.wav-contains nan
6_0.wav-contains nan
6_1.wav-contains nan
6_2.wav-contains nan
6_3.wav-contains nan
6_5.wav-contains nan
7_0.wav-contains nan
7_1.wav-contains nan
now-169,all-160,7_1.wav,(149, 256)
7_2.wav-contains nan
7_4.wav-contains nan
8_0.wav-contains nan
8_1.wav-contains nan
8_3.wav-contains nan
8_4.wav-contains nan
9_1.wav-contains nan
9_2.wav-contains nan
all-feature-done

Traceback (most recent call last):
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/train_nsf_sim_cache_sid_load_pretrain.py", line 7, in <module>
    hps = utils.get_hparams()
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/train/utils.py", line 363, in get_hparams
    config = json.loads(data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 47 column 1 (char 1047)
Traceback (most recent call last):
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/blocks.py", line 1039, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/lib/python3.10/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/home/user/Retrieval-based-Voice-Conversion-WebUI/infer-web.py", line 894, in train1key
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by fumiama** [comment]
- Try to increase the volume to avoid RVC cutting your normal voice out as silence.
- You got a `nan` result, so your wav or graphic card may be incompatible for training. @RVC-Boss will tell you whether we can fix that.

**Comment by mr-segfault** [comment]
Alright, volume wise I've run https://github.com/henrymaas/AudioSlicer/ on my dataset so any silences were already stripped out and then ran the samples into a gentle saturator plugin, they are quite punchy and loud. 

I'm attempting to re-running this with 2,034 samples ~ 4 hours of data and will see if it works better that way.

I'll also try to run this on another PC with more powerful dual GPU tomorrow am. 

Thank you for taking a look at these.

**Comment by mr-segfault** [comment]
Another observation I had was that this exact dataset and computer with previous versions of RVC was able to train models (just not output an index file) but that training feature seems to have regressed despite RVC previously being capable of doing so.

**Comment by mr-segfault** [comment]
Still on my first PC but it's saying a lot of samples are, for example:
`1649_5.wav-contains nan`

These samples had previously been recognized just fine, something might be wrong with how it's processing samples which is screwing up training. Unsure if that's related to the .index file failing to write but my initial assumption is it's a processing step causing issues.

**Comment by RVC-Boss** [comment]
@mr-segfault 
16xx GPU can't extract half precision tensor feature. Nothing extracted and nothing trained.

You can try replace all ".half" to ".float" in the file "extract_feature_print.py"

**Comment by MagicGJ** [comment]
Same issue here, but why 1070ti is recognized as 16xx GPU?

**Comment by MagicGJ** [comment]
> 

Still have the error using 1070ti after replacing to ".float"
```
move model to cuda
all-feature-2111
all-feature-done

Traceback (most recent call last):
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\train_nsf_sim_cache_sid_load_pretrain.py", line 7, in <module>
    hps = utils.get_hparams()
  File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\train\utils.py", line 363, in get_hparams
    config = json.loads(data)
  File "e:\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "e:\anaconda3\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 47 column 1 (char 1046)
```

**Comment by ifgcguitarclub** [comment]
> 50 files ~ 6 minutes is too short?

yes...

**Comment by RVC-Boss** [comment]
> > 
> 
> Still have the error using 1070ti after replacing to ".float"
> 
> ```
> move model to cuda
> all-feature-2111
> all-feature-done
> 
> Traceback (most recent call last):
>   File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\train_nsf_sim_cache_sid_load_pretrain.py", line 7, in <module>
>     hps = utils.get_hparams()
>   File "E:\PycharmProjects\Retrieval-based-Voice-Conversion-WebUI\train\utils.py", line 363, in get_hparams
>     config = json.loads(data)
>   File "e:\anaconda3\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "e:\anaconda3\lib\json\decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 47 column 1 (char 1046)
> ```

I have fixed it. Download the latest "config.py"and replace it.

**Comment by mr-segfault** [comment]
Closing as this has been fixed. Thank you developers.

**Comment by tzwel** [comment]
this is still occurring to me, no idea how to troubleshoot. I managed to get it to work **once**, no idea how

**Comment by alfrentgen** [comment]
I was getting the "contains nan" message during feature extraction on my GTX 1660 Ti. I use master branch (commit 050ffd07e84a2227718a5cc6e7c7552bcdf2c10a). Fixed it with changing **extract_feature_print.py** lines containing ".half()", just removed. Seems there is a bug, because the code in the file is agnostic towards GPU half-precision ability.

**Comment by cahayamahardika16** [comment]
Got it more issues bug RVCv2 Disconnected
![Image](https://github.com/user-attachments/assets/5051257a-c8ff-46bf-b5ce-93067f696916)
