### ISSUE TITLE
poetry 构建环境  fairseq  错误

### ISSUE THREAD

**Issue by Dancetofigureoutyourshadow** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#2225]
WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from fairseq==0.12.2->-r requirements-dml.txt (line 7)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
  Using cached omegaconf-2.0.5-py3-none-any.whl.metadata (3.0 kB)
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq==0.12.2->-r requirements-dml.txt (line 7)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements-dml.txt (line 7) and fairseq because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq 0.12.2 depends on omegaconf<2.1
    hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by NaGaii1994** [comment]
When I tried to build via docker and pip, I got same error.
After downgrading pip to version 24.0, the problem was resolved.

<details><summary>pip error when docker build</summary>

```
19.94 WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
19.94 Requested omegaconf<2.1 from https://files.pythonhosted.org/packages/e5/f6/043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl (from fairseq==0.12.2->-r requirements.txt (line 7)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
19.94     PyYAML (>=5.1.*)
19.94             ~~~~~~^
19.94 Please use pip<24.1 if you need to use this version.
19.94 INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
19.95 ERROR: Cannot install -r requirements.txt (line 7) and fairseq because these package versions have conflicting dependencies.
19.95
19.95 The conflict is caused by:
19.95     fairseq 0.12.2 depends on omegaconf<2.1
19.95     hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5
19.95
19.95 To fix this you could try to:
19.95 1. loosen the range of package versions you've specified
19.95 2. remove package versions to allow pip to attempt to solve the dependency conflict
19.95
20.01 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
Dockerfile:31
--------------------
  29 |     RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
  30 |
  31 | >>> RUN python3 -m pip install --no-cache-dir -r requirements.txt
  32 |
  33 |     RUN aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/pretrained_v2/D40k.pth -d assets/pretrained_v2/ -o D40k.pth
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
ERROR: Service 'rvc' failed to build : Build failed
```　
</details>

**Comment by werbals** [comment]
Have the same problem :( Tried 20.4 pip version then 24.0, but no improvement. Tried to lower hydra-core version, also didn't help, tried to lover fairseq version, still error persist. Don't understand what changes I need to make.

**Comment by mdkberry** [comment]
still seeing this issue installing now

**Comment by RVC-Boss** [comment]
You can update the code to the latest `main` branch, where this issue has already been resolved. The latest `main` branch has resolved the dependency issues. Fairseq is not need now.
