### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by SamPro07** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#468]
C:\Users\Sameer\Downloads\RVC-beta-v2-0528>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897
loading weights/Joker_D_2333333.pth
Traceback (most recent call last):
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict    output = await app.blocks.process_api(
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\infer-web.py", line 405, in get_vc
    tgt_sr = cpt["config"][-1]
KeyError: 'config'
Traceback (most recent call last):
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\infer-web.py", line 184, in vc_single
    audio_opt = vc.pipeline(
NameError: name 'vc' is not defined

Traceback (most recent call last):
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict    output = await app.blocks.process_api(
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\components.py", line 2076, in postprocess
    processing_utils.audio_to_file(sample_rate, data, file.name)
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 206, in audio_to_file
    data = convert_to_16_bit_wav(data)
  File "C:\Users\Sameer\Downloads\RVC-beta-v2-0528\runtime\lib\site-packages\gradio\processing_utils.py", line 219, in convert_to_16_bit_wav
    if data.dtype in [np.float64, np.float32, np.float16]:
AttributeError: 'NoneType' object has no attribute 'dtype'

crepe harvest or pm don't work

**Comment by RVC-Boss** [comment]
Is weights/Joker_D_2333333.pth a 60MB+ file?

**Comment by nonametao** [comment]
Same error, I think there is something wrong with the newest version webui when training models, I have tried v1 and v2 models, both have the same error when using them, I am pretty sure that I use the right 60M model.

**Comment by RVC-Boss** [comment]
It may alse because nof0model+protect. Try protect=0.5? (This issue is fixed in 0618version.)

**Comment by Rainbowgunsh** [comment]
I fixed the issue. You need to add ".wav" to the end of your file (if wav) EXAMPLE: \instrument_Balling song.mp3_10.wav <-- add wav to end of directory NOT rename. If mp3 do ".mp3" etc etc

**Comment by skywalker454** [comment]
any  suggestion for this issue  ??

**Comment by Nima0mr** [comment]
Downloaded the new 0618 version but the issue is still there. @RVC-Boss

**Comment by HardikJain02** [comment]
temporary solution-

rerun `python infer-web.py` until it works. there will still be this error but the output will be shown. For me, 1 in 4 rerun works.

**Comment by rayehan1123** [comment]
Hello HardikJain02, may I ask you about how do I do that? It would be a pleasure if you could help me with this, thanks.

**Comment by HardikJain02** [comment]
> Hello HardikJain02, may I ask you about how do I do that? It would be a pleasure if you could help me with this, thanks.

In the terminal, you have to run `python infer-web.py` or `go-web.bat`. Now on WebUI when you click on the training button, if there's no expected output then repeat the whole process. It's just like nagging with your tv remote when the battery cells are down.

**Comment by rayehan1123** [comment]
Thanks for replying, I'm going to try this several times. Thanks a lot!

**Comment by Hellzicke** [comment]
It might be a GPU error? 
I had exact same issue with my GTX 980 Ti 6gb, problem gone with my RTX 4070 12gb

**Comment by SocksAndStuff** [comment]
Really wish this joke of a program could actually work, in the same boat

**Comment by GH0STSecurity** [comment]
im having the same problem, any idea?

**Comment by GianlucaApollaro** [comment]
Hello, the same problem started today for me today out of nowhere. If I use the cpu everything is fine, but when I attempt to use my nvidia rtx 3070 gpu then it goes crazy with this error. I'm using RVC1006Nvidia. Is there anything I can try? Thanks. It worked fine until yesterday and I changed absolutely nothing on my system.

**Comment by grayleeeeee** [comment]
> 我修复了这个问题。您需要在文件末尾添加“.wav”（如果是 wav）示例：\instrument_Balling song.mp3_10.wav <-- 将 wav 添加到目录末尾，而不是重命名。如果是 mp3，请添加“.mp3”等等

不是这个问题，前面用的好好的，突然就跳出这个问题，然后就一直不行了
